name: flutter_tdd_mango
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter 
  http:
  provider: 4.3.2+3
  equatable: 1.2.5
  get: 3.4.2
  carousel_slider: 2.3.1
  intl: 0.16.1  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.0
  mockito: 3.0.2
  faker: 1.3.0
flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
